# These are supported funding model platforms
# github: arebach
# patreon: # Replace with a Patreon username
# open_collective: # Replace with a Collective slug
# ko_fi: # Replace with Ko-fi username
# tidelift: # Replace with Tidelift account name
# community_bridge: # Replace with Community Bridge username
# liberapay: # Replace with Liberapay username
# issuehunt: # Replace with Issuehunt username
# lfx_counseling: # Replace with LFX Counseling username
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
